import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

const STATUS_DOC_PATH = "docs/status.md";
const STATUS_COMMIT_SUBJECT = "docs: refresh status page";
const SHIPMENT_LIMIT = 8;

function git(args) {
  return execFileSync("git", args, { encoding: "utf8" }).trim();
}

function readSection(filePath, heading) {
  const content = readFileSync(filePath, "utf8");
  const escapedHeading = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const pattern = new RegExp(
    `^## ${escapedHeading}\\n([\\s\\S]*?)(?=^## |\\Z)`,
    "m",
  );
  const match = content.match(pattern);

  if (!match) {
    throw new Error(`Missing section "${heading}" in ${filePath}`);
  }

  return match[1]?.trim() ?? "";
}

function extractBulletList(section) {
  const items = [];

  for (const line of section.split("\n")) {
    if (line.startsWith("- ")) {
      items.push(line.slice(2).trim());
      continue;
    }

    if (/^\s{2,}\S/.test(line) && items.length > 0) {
      items[items.length - 1] = `${items[items.length - 1]} ${line.trim()}`;
    }
  }

  return items;
}

function normalizeTitle(subject, body) {
  const mergeMessage = subject.match(/^Merge pull request #\d+/i);

  if (mergeMessage) {
    const bodyTitle = body
      .split("\n")
      .map((line) => line.trim())
      .find(Boolean);

    return bodyTitle ? bodyTitle.replace(/^\[codex\]\s*/i, "") : subject;
  }

  return subject.replace(/\s+\(#\d+\)$/, "").replace(/^\[codex\]\s*/i, "").trim();
}

function parsePullRequestNumber(subject) {
  const squashMatch = subject.match(/\(#(\d+)\)$/);
  if (squashMatch) {
    return squashMatch[1];
  }

  const mergeMatch = subject.match(/^Merge pull request #(\d+)/i);
  return mergeMatch?.[1];
}

export function resolveStatusHistoryRef() {
  try {
    const remoteHead = git(["symbolic-ref", "--quiet", "refs/remotes/origin/HEAD"]);

    if (remoteHead.startsWith("refs/remotes/")) {
      return remoteHead.slice("refs/remotes/".length);
    }
  } catch {}

  for (const fallbackRef of ["origin/main", "origin/master", "HEAD"]) {
    try {
      git(["rev-parse", "--verify", fallbackRef]);
      return fallbackRef;
    } catch {}
  }

  throw new Error("Could not resolve a branch or ref for status history.");
}

export function branchNameFromHistoryRef(historyRef) {
  return historyRef.split("/").at(-1) ?? historyRef;
}

export function loadRecentShipments(historyRef = resolveStatusHistoryRef()) {
  const records = git([
    "log",
    "--first-parent",
    "--date=short",
    `--grep=^${STATUS_COMMIT_SUBJECT}$`,
    "--invert-grep",
    "--pretty=format:%H%x1f%ad%x1f%s%x1f%b%x1e",
    "-20",
    historyRef,
  ])
    .split("\x1e")
    .map((record) => record.trim())
    .filter(Boolean);

  return records.slice(0, SHIPMENT_LIMIT).map((record) => {
    const [commit, date, subject, body = ""] = record.split("\x1f");
    const prNumber = parsePullRequestNumber(subject);

    return {
      commit,
      shortCommit: commit.slice(0, 7),
      date,
      prNumber,
      subject,
      title: normalizeTitle(subject, body),
    };
  });
}

function remoteToHttp(url) {
  if (url.startsWith("git@github.com:")) {
    return `https://github.com/${url.slice("git@github.com:".length).replace(/\.git$/, "")}`;
  }

  return url.replace(/\.git$/, "");
}

export function renderStatusDocument({
  defaultBranch,
  latestShipment,
  readmeCapabilities,
  recentShipments,
  repoUrl,
  roadmapNow,
  roadmapNext,
}) {
  const recentShippedTable = recentShipments
    .map((shipment) => {
      const prCell = shipment.prNumber
        ? `[#${shipment.prNumber}](${repoUrl}/pull/${shipment.prNumber})`
        : "Direct push";

      return `| ${shipment.date} | ${prCell} | ${shipment.title} | \`${shipment.shortCommit}\` |`;
    })
    .join("\n");

  return `# Quorum Status

> This file is generated by \`npm run status:refresh\`. Do not edit it by hand.

## Snapshot

- Product stage: early MVP CLI for enterprise AI claim verification
- Default branch: \`${defaultBranch}\`
- Latest shipped change: \`${latestShipment.shortCommit}\` on ${latestShipment.date}, ${latestShipment.title}
- CI: [![CI](${repoUrl}/actions/workflows/ci.yml/badge.svg)](${repoUrl}/actions/workflows/ci.yml)

## Current Capabilities

${readmeCapabilities.map((item) => `- ${item}`).join("\n")}

## Roadmap Snapshot

### Now

${roadmapNow.map((item) => `- ${item}`).join("\n")}

### Next In docs/roadmap.md

${roadmapNext.map((item) => `- ${item}`).join("\n")}

## Recently Shipped

| Date | PR | Change | Commit |
| --- | --- | --- | --- |
${recentShippedTable}
`;
}

export function updateStatus() {
  const historyRef = resolveStatusHistoryRef();
  const recentShipments = loadRecentShipments(historyRef);
  const latestShipment = recentShipments[0];

  if (!latestShipment) {
    throw new Error(`No shipped commits found on ${historyRef}`);
  }

  const repoUrl = remoteToHttp(git(["remote", "get-url", "origin"]));
  const capabilities = extractBulletList(readSection("docs/cli-guide.md", "Capability Index"));
  const roadmapNow = extractBulletList(readSection("docs/roadmap.md", "Now"));
  const roadmapNext = extractBulletList(readSection("docs/roadmap.md", "Next"));
  const statusDocument = renderStatusDocument({
    defaultBranch: branchNameFromHistoryRef(historyRef),
    latestShipment,
    readmeCapabilities: capabilities,
    recentShipments,
    repoUrl,
    roadmapNow,
    roadmapNext,
  });

  writeFileSync(STATUS_DOC_PATH, `${statusDocument}\n`, "utf8");
}

if (import.meta.url === new URL(process.argv[1], "file:").href) {
  updateStatus();
}
