export { verifyAnswer } from "./claim-verifier.js";
export type {
  AtomicClaim,
  BatchVerificationReport,
  BatchVerificationRunResult,
  BatchVerificationResult,
  ClaimAssessment,
  ClaimVerdict,
  EvidenceSnippet,
  SingleVerificationResult,
  SourceDocument,
  SourceTrustLevel,
  VerificationReport,
} from "./domain.js";
export {
  evaluateFixtureContent,
  evaluateFixtureContentResult,
  evaluateFixture,
  evaluateFixtureResult,
  evaluateFixtureContents,
  evaluateFixtureContentsResult,
  evaluateFixtures,
  evaluateFixturesResult,
  evaluateFixtureFiles,
  evaluateFixtureFilesResult,
  evaluateFixtureFile,
  evaluateFixtureFileResult,
  hasEvaluationMismatch,
  renderEvaluationHtmlReport,
  loadEvaluationFixture,
  loadEvaluationFixtureFromContent,
  renderEvaluationMarkdownReport,
  renderEvaluationTextReport,
  renderEvaluationScorecard,
  renderEvaluationSummaryCsv,
  resolveEvaluationFixturePaths,
} from "./evaluation.js";
export type {
  EvaluationBatchOptions,
  EvaluationBatchRunResult,
  EvaluationClaimScore,
  EvaluationFixture,
  EvaluationFixtureRunResult,
  InMemoryEvaluationFixtureFileOptions,
  InMemoryEvaluationFixtureFileBatchOptions,
  InMemoryEvaluationFixtureInput,
  InMemoryEvaluationBatchOptions,
  EvaluationScorecard,
} from "./evaluation.js";
export {
  importReviewerDecisions,
  importReviewerDecisionsResult,
  renderReviewerDecisionImportHtmlReport,
  renderReviewerDecisionImportMarkdownReport,
  renderReviewerDecisionImportReport,
  renderReviewerDecisionImportSummaryCsv,
} from "./reviewer-decision-import.js";
export type {
  ImportedReviewerDecision,
  ReviewerDecisionGroup,
  ReviewerDecisionImportReport,
  ReviewerDecisionImportResult,
} from "./reviewer-decision-import.js";
export {
  renderBatchHtmlReport,
  renderBatchMarkdownReport,
  renderBatchReviewerDecisionCsv,
  renderBatchSummaryCsv,
  renderHtmlReport,
  renderMarkdownReport,
  renderReviewerDecisionCsv,
  renderSummaryCsv,
  renderTextReport,
} from "./report-renderer.js";
export {
  CLAIM_VERDICTS,
  matchingFailVerdicts,
  parseClaimVerdict,
  shouldFailReport,
} from "./report-policy.js";
export type { FailPolicyReport } from "./report-policy.js";
export {
  importReviewerDecisionFile,
  importReviewerDecisionContents,
  importReviewerDecisionContentsResult,
  importReviewerDecisionFileResult,
  verifyAnswerBatchFileInputs,
  verifyAnswerBatchFileInputsResult,
  loadSourceDocuments as loadSources,
  loadSourceDocumentsFromContent as loadSourcesFromContent,
  resolveAnswerPaths,
  resolveSourcePaths,
  STDIN_ANSWER_PATH,
  verifyAnswers,
  verifyAnswersResult,
  verifyAnswerFileResult,
  verifyAnswerFileInputs,
  verifyAnswerFileInputsResult,
  verifyAnswerBatchContents,
  verifyAnswerBatchContentsResult,
  verifyAnswerContents,
  verifyAnswerContentsResult,
  verifyAnswerFile,
  verifyAnswerResult,
  verifyBatchAnswersResult as verifyAnswerBatchResult,
  verifyBatchAnswers as verifyAnswerBatch,
} from "./workflow.js";
export type {
  BatchFileInputVerificationOptions,
  BatchFileInputVerificationResultOptions,
  BatchVerificationOptions,
  InMemoryAnswerInput,
  InMemoryBatchContentVerificationOptions,
  InMemoryBatchVerificationOptions,
  InMemorySourceInput,
  InMemorySourceLoadOptions,
  ReviewerDecisionContentImportOptions,
  ReviewerDecisionContentImportResultOptions,
  ReviewerDecisionFileImportOptions,
  ReviewerDecisionFileImportResultOptions,
  SingleFileInputVerificationOptions,
  SingleFileInputVerificationResultOptions,
  SingleFileVerificationOptions,
  SingleVerificationResultOptions,
  InMemorySingleVerificationOptions,
  SourceLoadOptions,
} from "./workflow.js";
export { parseSource, parseSourceTrustLevel, sourceDocumentFromFile } from "./source-loader.js";
